### ISSUE TITLE
the example didn't work

### ISSUE THREAD

**Issue by xdsoar** [mjbvz/vscode-fenced-code-block-grammar-injection-example#1]
VSCode version:1.15.1
OS version: Windows 10 

Hi there, I have just downloaded the example and copy it to my vscode folder under ".vscode/extensions/".I can find the extension in the extensions list, But just didn't get highlight code in code block begin with superjs.
I also find in the file "package.json", there is a specific path "./syntaxes/test.json" which is not exists. Should I change the path to somthing else or just add this file?

**Comment by mjbvz** [comment]
Yes the incorrect name was used for the file. It should be fixed now

**Comment by xdsoar** [comment]
Yes, the example works now.
But I still wonder how can I change the syntax source `source.js` to my own syntax file?
Is there any document about this grammar injection feature?
