### ISSUE TITLE
Markdown Preview does not show highlighted code

### ISSUE THREAD

**Issue by ghost** [mjbvz/vscode-fenced-code-block-grammar-injection-example#17]
I was able to get my language to highlight within the .md file, but when I go to view the rendered preview, the code is still not being highlighted.

![image](https://user-images.githubusercontent.com/95868869/173123847-e58c77c3-1422-4774-bbc5-3a734c16d190.png)

**Comment by mjbvz** [comment]
This is expected. This repo is about modifying the text mate grammar VS Code uses for highlighting code in the editor

The preview uses highlight.js for code highlighting so won't be effected by this. See https://github.com/microsoft/vscode/issues/91279
