### ISSUE TITLE
What's wrong with my syntax highlighting grammar injection?

### ISSUE THREAD

**Issue by colinfang** [mjbvz/vscode-fenced-code-block-grammar-injection-example#2]
Sorry this is not a bug. I would like to ask you for some help regarding the grammar injection syntax as I couldn't find any relevant resources.

I am following `codeblock.json` for a simple grammar injection in markdown.

There is a small problem with the above code - As long as there is a string superjs appear in the fenced code block, the remaining would always be rendered as superjs, which would break fenced code block syntax highlighting for other embedded languages.

~~~markdown
```json
{
   "foo": "superjs"
}
```
~~~

I would like to fix it by following https://github.com/Microsoft/vscode/blob/master/extensions/markdown/syntaxes/markdown.tmLanguage

```json
"fileTypes": [],
"injectionSelector": "text.html.markdown",
"patterns": [
    {
        "include": "#fenced_code_block_superjs"
    }
],
"repository": {
    "fenced_code_block_superjs": {
        "begin": "(^|\\G)(\\s*)(`{3,}|~{3,})\\s*(?i:(superjs)(\\s+[^`~]*)?$)", 
        "beginCaptures": {
            "3": {
                "name": "punctuation.definition.markdown"
            }, 
            "5": {
                "name": "fenced_code.block.language"
            }, 
            "6": {
                "name": "fenced_code.block.language.attributes"
            }
        }, 
        "end": "(^|\\G)(\\2|\\s{0,3})(\\3)\\s*$", 
        "endCaptures": {
            "3": {
                "name": "punctuation.definition.markdown"
            }
        }, 
        "name": "markup.fenced_code.block.markdown", 
        "patterns": [
            {
                "begin": "(^|\\G)(\\s*)(.*)", 
                "contentName": "meta.embedded.block.superjs", 
                "patterns": [
                    {
                        "include": "source.js"
                    }
                ], 
                "while": "(^|\\G)(?!\\s*([`~]{3,})\\s*$)"
            }
        ]
    }
},
"scopeName": "markdown.superjs.codeblock"
```

However it doesn't work, and I don't know how to debug it either.

The related stackoverflow post: 

https://stackoverflow.com/questions/47418275/whats-wrong-with-my-syntax-highlighting-grammar-injection

**Comment by colinfang** [comment]
nvm, it is the rule priority issue.

**Comment by kachkaev** [comment]
@colinfang how did you fix it? Facing exactly the same issue now. If your extension is public, a link to its source would help!

**Comment by kachkaev** [comment]
Found your answer here: https://stackoverflow.com/a/47502368/1818285 :tada:

The example in this repo looks outdated indeed.
