### ISSUE TITLE
Supporting aliases

### ISSUE THREAD

**Issue by glebec** [mjbvz/vscode-fenced-code-block-grammar-injection-example#4]
Following these steps I was able to get `haskell` to work properly. I want to also add `hs` – is there any way to reuse a single `json` file and/or `grammar` config to support both aliases, or do I need to create a brand new copy of each? It's fine if the latter is the case, just checking. Thanks!

**Comment by mjbvz** [comment]
Yes, just use `(haskell|hs)` in the syntax's  `begin` rule.

**Comment by glebec** [comment]
Thanks @mjbvz!
