### ISSUE TITLE
false positives for superstrings

### ISSUE THREAD

**Issue by glebec** [mjbvz/vscode-fenced-code-block-grammar-injection-example#5]
If we use an identifier `foo`, it will currently also match `ofoo`, `abcdefghfoo`, etc.

This is potentially problematic, e.g. for `hs` (Haskell) vs. `lhs` (Literate Haskell).

**Comment by mjbvz** [comment]
It’s just a regular expression so you can do something like `\bfoo\b` if you want the matching to be more strict

**Comment by glebec** [comment]
Closing accordingly, though you may want to consider making that the default.

Also, for some reason I am having trouble getting this to work with `cabal`, `lhs` etc. — though it worked fine for `haskell`. I might link a repo here to see if you can help me out (if it's not too inconvenient).

**Comment by glebec** [comment]
@mjbvz not sure where is the best place to put this – hijacking this closed issue to do so, but happy to delete this message and send via alternate means if you prefer.

In [this diff](https://github.com/glebec/language-haskell/compare/d61be4ddaff7...demo/failing-cabal) I've added working Haskell support to the `language-haskell` extension. But for some reason Cabal support fails. I've gone over the substitutions with a fine-toothed comb and they map one-to-one, so at this point I start to wonder if there is something deeper at play with how the `tmLanguage` files / scopes / etc. all interplay that is beyond my current understanding of what all these configuration keys are actually doing.

I appreciate any insight you may be able to provide. I recognize this isn't an issue with your work here, so if you cannot spare the time I understand. Regards, —G.

**Comment by mjbvz** [comment]
[This line](https://github.com/glebec/language-haskell/blob/bce7311a3ee1a539838c27b3988644a25adc3ed9/syntaxes/codeblock-cabal.json#L10) needs to be `"cabal-code-block"` instead of `"haskell-code-block"`

**Comment by glebec** [comment]
Well that’s pretty simple! Embarrassed to have missed it, but thank you for pointing it out.
