### ISSUE TITLE
Syntax highlighting of injected language not shown in Preview

### ISSUE THREAD

**Issue by ThFriedrich** [mjbvz/vscode-fenced-code-block-grammar-injection-example#7]
Thanks @mjbvz  for this super helpful example. 
Running the example as it is I get the following behavior:
![image](https://user-images.githubusercontent.com/47680554/86132330-06a66000-bae7-11ea-98d5-19a00b03246d.png)
It seems within the md.-file the injected Syntax is highlighted but in the Preview, it isn't. Is that by design? Is it possible to transfer the Syntax highlighting functionality into the Preview as well? 

My Setup:
Version: 1.46.1
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-61-generic

**Comment by mjbvz** [comment]
This is a known limitation. The markdown preview uses highlight.js for highlighting, not VS Code's highlighting

**Comment by mjbvz** [comment]
Closing this as this is current design of VS Code.

https://github.com/microsoft/vscode/issues/56356 would let the preview use VS Code's built-in highlighter instead

**Comment by tjpalmer** [comment]
For those finding this in the future, the [mermaid markdown example](https://github.com/mjbvz/vscode-markdown-mermaid/blob/9058dc44792c28fe49f582f4bc9b3c153e62cd6d/src/index.ts#L49) also by @mjbvz shows where to plug in custom syntax highlighting in markdown preview. And [vscode-textmate](https://www.npmjs.com/package/vscode-textmate) can be used to adapt tokens to hljs class names. It would be nice if vscode did this automatically, but it's possible to wire up manually at this point.

**Comment by ThFriedrich** [comment]
Thanks @tjpalmer 
I had reached a very similar conclusion back then, indeed using [vscode-textmate](https://www.npmjs.com/package/vscode-textmate) and [vscode-oniguruma](https://www.npmjs.com/package/vscode-oniguruma). You can check the [StackOverflow Question](https://stackoverflow.com/questions/62328182/is-there-a-way-to-use-a-tmlanguage-grammar-to-extend-vscode-integrated-markdown/63917625#63917625) and [my implementation](https://github.com/ThFriedrich/lammps_vscode/blob/master/src/highlight_fcns.ts) for the details.
