### ISSUE TITLE
Adding support for Gherkin in Markdown files

### ISSUE THREAD

**Issue by dialex** [mjbvz/vscode-fenced-code-block-grammar-injection-example#9]
Hi @mjbvz, we want to have [Gherkin syntax highlight in Markdown code blocks](https://github.com/euclidity/vscode-cucumber/issues/26#issuecomment-738669740).

This feature was previously requested at https://github.com/microsoft/vscode/issues/23055#issuecomment-369475841 and now we're trying to implement it in this [extension](https://marketplace.visualstudio.com/items?itemName=stevejpurves.cucumber).

We tried to follow [your README](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example#how-to-modify-this-repo-to-support-a-new-language-in-fenced-code-blocks), but it didn't work. Can you please [code review](https://github.com/euclidity/vscode-cucumber/commit/26380c470873b051522a82e5e4577e7455f5d746) our `codeblock.json` and tell us where we messed up?

For me steps 2-4 were the most confusing. I skipped step 6 because I don't have a `embeddedLanguages` field anywhere.

We would appreciate if you could help us. Thanks.

**Comment by mjbvz** [comment]
Your `package.json` seems wrong. There should be two grammar entries: the main one and one for the injection grammar

Right now it looks like there is just one and no references to the new `codeblock` grammar file:

https://github.com/euclidity/vscode-cucumber/compare/add-md-code-block-syntax-highlight#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R57
